"""empty message

Revision ID: 25f9e7a1e58e
Revises: a872583713eb
Create Date: 2021-04-16 14:00:16.297943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f9e7a1e58e'
down_revision = 'a872583713eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learned_words', sa.Column('practiced', sa.Integer(), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('learned_words', 'practiced')
    # ### end Alembic commands ###
